#!/usr/bin/env bash
# install a nginx server listening on port 80.
#
# Also, when querying nginx at its root/ with a GET
# request, it returns a page that contains the string
# 'Hello World'.
#

apt-get update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
